decree/urls.py
from django.urls import path

from .views import (decree_list,
                    decree_create,
                    decree_detail,
                    decree_changed_create,
                    decree_changed_detail)

app_name = 'decree'

urlpatterns = [
    path('', decree_list, name='decree_list'),
    path('create/', decree_create, name='decree_create'),
    path('detail/<int:decree_id>/', decree_detail, name='decree_detail'),
    path('detail/<int:decree_id>/create_changed/',
         decree_changed_create,
         name='decree_changed_create'),
    path('detail/<int:decree_id>/detail_changed/<int:decree_changed_id>',
         decree_changed_detail,
         name='decree_changed_detail')
]

decreeMNPCBT/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('decree.urls')),
    path('auth/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from django.contrib.auth.views import (
    LogoutView,
    LoginView,
)

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SingUp.as_view(), name='signup'),
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

decree/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Type(models.Model):
    """Тип документа"""
    title = models.CharField("Тип документа", max_length=150)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Тип документа'
        verbose_name_plural = 'Тип документа'


class Decrees(models.Model):
    """Приказы"""
    type = models.ForeignKey(
        Type,
        verbose_name="Тип документа",
        null=True,
        on_delete=models.SET_NULL,
        related_name="decree_type"
    )
    title = models.CharField("Название", max_length=200)
    number = models.IntegerField("Номер")
    date_create = models.DateField()
    pub_date = models.DateField(auto_now_add=True)
    file = models.FileField(
        "Файл",
        upload_to="decree/%Y/%m/%d/"
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='author_decree'
    )
    decree = models.ForeignKey('self',
                               on_delete=models.CASCADE,
                               related_name='main_decree',
                               null=True,
                               blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Приказ'
        verbose_name_plural = 'Приказы'


class DecreesChanged(models.Model):
    """Изменения в приказах"""
    type = models.ForeignKey(
        Type,
        verbose_name="Тип документа",
        null=True,
        on_delete=models.SET_NULL,
        related_name="decree_changed_type"
    )
    decree = models.ForeignKey(
        Decrees,
        verbose_name="Приказ",
        null=True,
        on_delete=models.SET_NULL,
        related_name="decree_changed_decree"
    )
    title = models.CharField("Название", max_length=200)
    number = models.IntegerField("Номер")
    date_create = models.DateField()
    pub_date = models.DateField(auto_now_add=True)
    file = models.FileField(
        "Файл",
        upload_to="decree/%Y/%m/%d/"
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='author_decree_changed'
    )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Изменения'
        verbose_name_plural = 'Изменения'

users/models.py
from django.db import models

# Create your models here.

decree/forms.py
from django import forms

from .models import Decrees


class DecreeForm(forms.ModelForm):
    class Meta:
        model = Decrees
        fields = ('type', 'title', 'number', 'file', 'author', 'decree')
        # help_texts = {
        #     'text': 'Текст нового поста',
        #     'group': 'Группа, к которой будет относиться пост'
        # }
        # labels = {
        #     'text': 'Текст поля',
        #     'group': 'Группа'
        # }

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

decree/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Count

from .models import Decrees, DecreesChanged, Type
from .forms import DecreeForm


@login_required()
def decree_list(request):
    """Главная страница"""
    decrees = Decrees.objects.all()
    types = Type.objects.annotate(sum_documents=Count('decree_type'))

    def count_documents():
        sum_count = []

        for type in types:
            if type.sum_documents > 0:
                sum_count.append(type.sum_documents)
        return sum_count

    context = {
        'title': 'Главная страница',
        'decrees': decrees,
        'types': types,
        'types_': count_documents(),
    }
    return render(request, 'decree/index.html', context)


@login_required()
def decree_create(request):
    """Добавить новый документ"""
    form = DecreeForm()
    context = {
        'title': 'Добавить документ',
        'form': form
    }
    return render(request, 'decree/create.html', context)


@login_required()
def decree_changed_create(request, decree_id):
    """Добавить новое внесение изменений"""
    form = DecreeForm()
    context = {
        'title': 'Добавить изменения',
        'form': form
    }
    return render(request, 'decree/create_changed.html', context)


@login_required()
def decree_detail(request, decree_id):
    """Детальный просмотр документа"""
    decree = get_object_or_404(Decrees, pk=decree_id)
    context = {
        'title': decree.title,
        'dec': decree
    }
    return render(request, 'decree/detail.html', context)


@login_required()
def decree_changed_detail(request, decree_id, decree_changed_id):
    """Детальный просмотр прикрепленного документа"""
    decree_changed = get_object_or_404(DecreesChanged, pk=decree_changed_id)
    context = {
        'title': decree_changed.title,
        'decree_changed': decree_changed
    }
    return render(request, 'decree/decree_changed_detail.html', context)

users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SingUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('decree:decree_list')
    template_name = 'users/signup.html'

decree/templates/decree/create.html
{% extends 'base.html' %}
{% block breadcrumbs %}
    {{ block.super }}
    <div class="page-intro single-col-max mx-auto"><i class="fa-solid fa-right-long"></i></div>
    <li>
        <div class="page-intro single-col-max mx-auto">{{ title }}</div>
    </li>
{% endblock %}
{% block content %}
    <div class="page-content">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-8 offset-md-2">
                    <form method="post"
                          enctype="multipart/form-data"
                          action="{% url 'decree:decree_create' %}">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group row my-3">
                                <label for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                    {% if field.field.required %}
                                        <span class="required text-danger">*</span>
                                    {% endif %}
                                </label>
                                {{ field }}
                                {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                        {{ field.help_text|safe }}
                                    </small>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div class="d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">
                                    Добавить
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

decree/templates/decree/create_changed.html
{% extends 'decree/create.html' %}
{% block breadcrumbs %}
    {{ block.super }}
    <div class="page-intro single-col-max mx-auto"><i class="fa-solid fa-right-long"></i></div>
    <li>
        <div class="page-intro single-col-max mx-auto">{{ title }}</div>
    </li>
{% endblock %}
{% block content %}
    <div class="page-content">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-8 offset-md-2">
                    <form method="post"
                          enctype="multipart/form-data"
                          action="{% url 'decree:decree_create' %}">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group row my-3">
                                <label for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                    {% if field.field.required %}
                                        <span class="required text-danger">*</span>
                                    {% endif %}
                                </label>
                                {{ field }}
                                {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                        {{ field.help_text|safe }}
                                    </small>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div class="d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary">
                                    Добавить
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

decree/templates/decree/detail.html
{% extends 'base.html' %}
{% block breadcrumbs %}
    {{ block.super }}
    <div class="page-intro single-col-max mx-auto"><i class="fa-solid fa-right-long"></i></div>
    <li>
        <div class="page-intro single-col-max mx-auto">{{ dec.title }}</div>
    </li>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <div class="callout-block callout-block-success">
                    <div class="content">
                        <h4 class="callout-title">
	                                <span class="callout-icon-holder me-1">
		                                <i class="fas fa-info-circle"></i>
		                            </span>
                            {{ dec.title }}
                        </h4>
                    </div>
                </div>
                <div class="callout-block callout-block-success">
                    <div class="content">
                        <h4 class="callout-title">
	                                <span class="callout-icon-holder me-1">
		                                №
		                            </span>
                            {{ dec.number }}
                        </h4>
                    </div>
                </div>
                <div class="callout-block callout-block-success">
                    <div class="content">
                        <h4 class="callout-title">
	                                <span class="callout-icon-holder me-1">
		                                <i class="fa-solid fa-calendar"></i>
		                            </span>
                            {{ dec.pub_date }}
                        </h4>
                    </div>
                </div>
                <div class="callout-block callout-block-success">
                    <div class="content">
                        <h4 class="callout-title">
	                                <span class="callout-icon-holder me-1">
		                               <i class="fa-sharp fa-solid fa-rectangle-history"></i>
		                            </span>
                            {{ dec.type }}
                        </h4>
                    </div>
                </div>
                <div class="callout-block callout-block-success">
                    <div class="content">
                        <h4 class="callout-title">
	                                <span class="callout-icon-holder me-1">
		                               <i class="fa-solid fa-user-large"></i>
		                            </span>
                            {{ dec.author.first_name }} {{ dec.author.last_name }}
                        </h4>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-6">
                {% if dec.decree %}
                    {{ dec.decree.title }}
                {% else %}
                    no!
                {% endif %}

                {% for d in dec.main_decree.all %}
                    {{ d.title }}
                {% endfor %}
                <div>
                    <a href="{% url 'decree:decree_changed_create' dec.pk %}">Внести изменения</a>
                </div>
            </div>
        </div>
        <iframe src="{{ dec.file.url }}" width="100%" height="600"></iframe>
    </div>
{% endblock %}

decree/templates/decree/index.html
{% extends 'base.html' %}
{% block content %}

    <div class="page-content">
        <div class="container">
            <div class="docs-overview py-5">
                <div class="owl-carousel owl-theme">
                    {% for decree in decrees %}
                        <div class="item">
                            <a href="{% url 'decree:decree_detail' decree.pk %}">
                                <h3>{{ decree.title }}</h3>
                                <h5>{{ decree.number }}</h5>
                            </a>
                        </div>
                    {% endfor %}
                </div>
                <div>
        <canvas id="myChart"></canvas>
    </div>
    <script>
        const ctx = document.getElementById('myChart');
        new Chart(ctx, {
            type: 'doughnut',
            data: {
                labels: [
                    {% for type in types %}
                        {% if type.sum_documents > 0 %}
                            '{{ type.title }}',
                        {% endif %}
                    {% endfor %}
                ],
                datasets: [{
                    data: {{ types_ }},
                    backgroundColor: [
                        'rgb(255, 99, 132)',
                        'rgb(54, 162, 235)',
                        'rgb(255, 205, 86)',
                        'rgb(255, 05, 186)',
                    ],
                    hoverOffset: 4
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    </script>
{#                <div class="row justify-content-center">#}
{#                    <div class="col-12 col-lg-4 py-3">#}
{#                        <div class="card shadow-sm">#}
{#                            <div class="card-body">#}
{#                                <h5 class="card-title mb-3">#}
{#								    <span class="theme-icon-holder card-icon-holder me-2">#}
{#								        <i class="fas fa-map-signs"></i>#}
{#							        </span><!--//card-icon-holder-->#}
{#                                    <span class="card-title-text">Introduction</span>#}
{#                                </h5>#}
{#                                <div class="card-text">#}
{#                                    Section overview goes here. Lorem ipsum dolor sit amet, consectetuer adipiscing#}
{#                                    elit. Aenean commodo ligula eget dolor.#}
{#                                </div>#}
{#                                <a class="card-link-mask" href="docs-page.html#section-1"></a>#}
{#                            </div><!--//card-body-->#}
{#                        </div><!--//card-->#}
{#                    </div><!--//col-->#}
{#                    <div class="col-12 col-lg-4 py-3">#}
{#                        <div class="card shadow-sm">#}
{#                            <div class="card-body">#}
{#                                <h5 class="card-title mb-3">#}
{#								    <span class="theme-icon-holder card-icon-holder me-2">#}
{#								        <i class="fas fa-arrow-down"></i>#}
{#							        </span><!--//card-icon-holder-->#}
{#                                    <span class="card-title-text">Installation</span>#}
{#                                </h5>#}
{#                                <div class="card-text">#}
{#                                    Section overview goes here. Donec pede justo, fringilla vel, aliquet nec, vulputate#}
{#                                    eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo.#}
{#                                </div>#}
{#                                <a class="card-link-mask" href="docs-page.html#section-2"></a>#}
{#                            </div><!--//card-body-->#}
{#                        </div><!--//card-->#}
{#                    </div><!--//col-->#}
{#                    <div class="col-12 col-lg-4 py-3">#}
{#                        <div class="card shadow-sm">#}
{#                            <div class="card-body">#}
{#                                <h5 class="card-title mb-3">#}
{#								    <span class="theme-icon-holder card-icon-holder me-2">#}
{#								        <i class="fas fa-box fa-fw"></i>#}
{#							        </span><!--//card-icon-holder-->#}
{#                                    <span class="card-title-text">APIs</span>#}
{#                                </h5>#}
{#                                <div class="card-text">#}
{#                                    Section overview goes here. Aliquam lorem ante, dapibus in, viverra quis, feugiat a,#}
{#                                    tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean#}
{#                                    imperdiet.#}
{#                                </div>#}
{#                                <a class="card-link-mask" href="docs-page.html#section-3"></a>#}
{#                            </div><!--//card-body-->#}
{#                        </div><!--//card-->#}
{#                    </div><!--//col-->#}
{#                    <div class="col-12 col-lg-4 py-3">#}
{#                        <div class="card shadow-sm">#}
{#                            <div class="card-body">#}
{#                                <h5 class="card-title mb-3">#}
{#								    <span class="theme-icon-holder card-icon-holder me-2">#}
{#								        <i class="fas fa-cogs fa-fw"></i>#}
{#							        </span><!--//card-icon-holder-->#}
{#                                    <span class="card-title-text">Integrations</span>#}
{#                                </h5>#}
{#                                <div class="card-text">#}
{#                                    Section overview goes here. Aliquam lorem ante, dapibus in, viverra quis, feugiat a,#}
{#                                    tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean#}
{#                                    imperdiet.#}
{#                                </div>#}
{#                                <a class="card-link-mask" href="docs-page.html#section-4"></a>#}
{#                            </div><!--//card-body-->#}
{#                        </div><!--//card-->#}
{#                    </div><!--//col-->#}
{#                    <div class="col-12 col-lg-4 py-3">#}
{#                        <div class="card shadow-sm">#}
{#                            <div class="card-body">#}
{#                                <h5 class="card-title mb-3">#}
{#								    <span class="theme-icon-holder card-icon-holder me-2">#}
{#								        <i class="fas fa-tools"></i>#}
{#							        </span><!--//card-icon-holder-->#}
{#                                    <span class="card-title-text">Utilities</span>#}
{#                                </h5>#}
{#                                <div class="card-text">#}
{#                                    Section overview goes here. Aliquam lorem ante, dapibus in, viverra quis, feugiat a,#}
{#                                    tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean#}
{#                                    imperdiet.#}
{#                                </div>#}
{#                                <a class="card-link-mask" href="docs-page.html#section-5"></a>#}
{#                            </div><!--//card-body-->#}
{#                        </div><!--//card-->#}
{#                    </div><!--//col-->#}
{#                    <div class="col-12 col-lg-4 py-3">#}
{#                        <div class="card shadow-sm">#}
{#                            <div class="card-body">#}
{#                                <h5 class="card-title mb-3">#}
{#								    <span class="theme-icon-holder card-icon-holder me-2">#}
{#								        <i class="fas fa-laptop-code"></i>#}
{#							        </span><!--//card-icon-holder-->#}
{#                                    <span class="card-title-text">Web</span>#}
{#                                </h5>#}
{#                                <div class="card-text">#}
{#                                    Section overview goes here. Aliquam lorem ante, dapibus in, viverra quis, feugiat a,#}
{#                                    tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean#}
{#                                    imperdiet.#}
{#                                </div>#}
{#                                <a class="card-link-mask" href="docs-page.html#section-6"></a>#}
{#                            </div><!--//card-body-->#}
{#                        </div><!--//card-->#}
{#                    </div><!--//col-->#}
{#                    <div class="col-12 col-lg-4 py-3">#}
{#                        <div class="card shadow-sm">#}
{#                            <div class="card-body">#}
{#                                <h5 class="card-title mb-3">#}
{#								    <span class="theme-icon-holder card-icon-holder me-2">#}
{#								        <i class="fas fa-tablet-alt"></i>#}
{#							        </span><!--//card-icon-holder-->#}
{#                                    <span class="card-title-text">Mobile</span>#}
{#                                </h5>#}
{#                                <div class="card-text">#}
{#                                    Section overview goes here. Aliquam lorem ante, dapibus in, viverra quis, feugiat a,#}
{#                                    tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean#}
{#                                    imperdiet.#}
{#                                </div>#}
{#                                <a class="card-link-mask" href="docs-page.html#section-7"></a>#}
{#                            </div><!--//card-body-->#}
{#                        </div><!--//card-->#}
{#                    </div><!--//col-->#}
{#                    <div class="col-12 col-lg-4 py-3">#}
{#                        <div class="card shadow-sm">#}
{#                            <div class="card-body">#}
{#                                <h5 class="card-title mb-3">#}
{#								    <span class="theme-icon-holder card-icon-holder me-2">#}
{#								        <i class="fas fa-book-reader"></i>#}
{#							        </span><!--//card-icon-holder-->#}
{#                                    <span class="card-title-text">Resources</span>#}
{#                                </h5>#}
{#                                <div class="card-text">#}
{#                                    Section overview goes here. Aliquam lorem ante, dapibus in, viverra quis, feugiat a,#}
{#                                    tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean#}
{#                                    imperdiet.#}
{#                                </div>#}
{#                                <a class="card-link-mask" href="docs-page.html#section-8"></a>#}
{#                            </div><!--//card-body-->#}
{#                        </div><!--//card-->#}
{#                    </div><!--//col-->#}
{#                    <div class="col-12 col-lg-4 py-3">#}
{#                        <div class="card shadow-sm">#}
{#                            <div class="card-body">#}
{#                                <h5 class="card-title mb-3">#}
{#								    <span class="theme-icon-holder card-icon-holder me-2">#}
{#								        <i class="fas fa-lightbulb"></i>#}
{#							        </span><!--//card-icon-holder-->#}
{#                                    <span class="card-title-text">FAQs</span>#}
{#                                </h5>#}
{#                                <div class="card-text">#}
{#                                    Section overview goes here. Aliquam lorem ante, dapibus in, viverra quis, feugiat a,#}
{#                                    tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean#}
{#                                    imperdiet.#}
{#                                </div>#}
{#                                <a class="card-link-mask" href="docs-page.html#section-9"></a>#}
{#                            </div><!--//card-body-->#}
{#                        </div><!--//card-->#}
{#                    </div><!--//col-->#}
{#                </div><!--//row-->#}
            </div><!--//container-->
        </div><!--//container-->
    </div><!--//page-content-->

    <section class="cta-section text-center py-5 theme-bg-dark position-relative">
        <div class="theme-bg-shapes-right"></div>
        <div class="theme-bg-shapes-left"></div>
        <div class="container">
            <h3 class="mb-2 text-white mb-3">Launch Your Software Project Like A Pro</h3>
            <div class="section-intro text-white mb-3 single-col-max mx-auto">Want to launch your software project and
                start getting traction from your target users? Check out our premium <a class="text-white"
                                                                                        href="https://themes.3rdwavemedia.com/bootstrap-templates/startup/coderpro-bootstrap-5-startup-template-for-software-projects/">Bootstrap
                    5 startup template CoderPro</a>! It has everything you need to promote your product.
            </div>
            <div class="pt-3 text-center">
                <a class="btn btn-light"
                   href="https://themes.3rdwavemedia.com/bootstrap-templates/startup/coderpro-bootstrap-5-startup-template-for-software-projects/">Get
                    CoderPro<i class="fas fa-arrow-alt-circle-right ml-2"></i></a>
            </div>
        </div>
    </section><!--//cta-section-->

{% endblock %}

templates/_include/header.html
<header class="header fixed-top">

    <div class="branding docs-branding">
        <div class="container-fluid position-relative py-2">
            <div class="docs-logo-wrapper">
                <div class="site-logo"><a class="navbar-brand" href="/"><img class="logo-icon me-2"
                                                                             src="/static/assets/images/logo_decree.png"
                                                                             alt="logo" style="width: 230px;">
                    {#                    <span class="logo-text">Coder<span class="text-alt">Docs</span></span>#}
                </a></div>
            </div><!--//docs-logo-wrapper-->
            <div class="docs-top-utilities d-flex justify-content-end align-items-center">
                {% if user.is_authenticated %}
                    <li class="me-5"><a href="{% url 'decree:decree_create' %}"><i class="fa-solid fa-plus"></i> Добавить документ</a></li>
                    <li>{{ user.first_name }} {{ user.last_name }}</li>
                    <a href="{% url 'users:logout' %}" class="btn btn-primary d-none d-lg-flex">Выйти</a>
                    {% else %}
                    <a href="{% url 'users:login' %}" class="btn btn-primary d-none d-lg-flex">Авторизация</a>
                {% endif %}

            </div><!--//docs-top-utilities-->
        </div><!--//container-->
    </div><!--//branding-->
</header><!--//header-->

templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Зарегистрироваться</div>
            <div class="card-body">
                {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}
                <div class="alert alert-danger">
                    {{ error|escape }}
                </div>
                {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    {{ error|escape }}
                </div>
                {% endfor %}
                {% endif %}
                <form method="post" action="{% url 'users:signup' %}">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group row my-3">
                        <label for="{{ field.id_for_label }}">
                            {{ field.label }}
                            {% if field.field.required %}
                            <span class="required text-danger">*</span>
                            {% endif %}
                        </label>
                        {{ field}}
                        {% if field.help_text %}
                        <small
                                id="{{ field.id_for_label }}-help"
                                class="form-text text-muted"
                        >
                            {{ field.help_text|safe }}
                        </small>
                        {% endif %}
                    </div>
                    {% endfor %}
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Зарегистрироваться
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}